#!/usr/bin/env bash
# Run ONCE on each display Pi. Boots the Pi into a full-screen browser showing
# one display's slice of one venue's wall.
#
#   ./setup-display-pi.sh <SERVER> <SITE> <DISPLAY_ID>
#   e.g.  ./setup-display-pi.sh wall.example.com live-rooms-1 3
#         ./setup-display-pi.sh 192.168.1.50   central-station 2
#
# Raspberry Pi OS Bookworm (labwc), Desktop image.

set -e
SERVER="${1:?usage: setup-display-pi.sh <SERVER> <SITE> <DISPLAY_ID>}"
SITE="${2:?usage: setup-display-pi.sh <SERVER> <SITE> <DISPLAY_ID>}"
ID="${3:?usage: setup-display-pi.sh <SERVER> <SITE> <DISPLAY_ID>}"
# add :8080 if you're hitting a bare IP/hostname without a reverse proxy
case "$SERVER" in *:*) HOST="$SERVER";; *) HOST="$SERVER:8080";; esac
URL="http://${HOST}/s/${SITE}/display/${ID}"

sudo apt-get update
sudo apt-get install -y chromium-browser unclutter

mkdir -p "$HOME/.config/labwc"
cat > "$HOME/.config/labwc/autostart" <<EOF
# auto-generated by setup-display-pi.sh — venue ${SITE}, display ${ID}
unclutter --timeout 1 &
chromium-browser --kiosk --incognito --noerrdialogs --disable-infobars \\
  --check-for-update-interval=31536000 --disable-features=Translate \\
  --autoplay-policy=no-user-gesture-required --app="${URL}" &
EOF

echo
echo "Done. This Pi will open ${URL} on next boot."
echo "Reboot:  sudo reboot"
